import Head from "next/head";

import { useEffect } from "react";
import io from "socket.io-client";
let socket;

const HomePage = () => {
  const socketInitializer = async () => {
    await fetch("/api/socket");
    socket = io("http://localhost:3000/home");

    socket.on("connect", () => {
      console.log("connected");
    });
  };

  useEffect(() => {
    socketInitializer()
      .then((m) => console.log(""))
      .catch((err) => console.error(err));
  }, []);

  return (
    <>
      <Head>
        <title>Basta App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-screen bg-oscuro"></main>
    </>
  );
};

export default HomePage;
