import { signIn } from "next-auth/react";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Basta App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-screen bg-oscuro">
        <button onClick={() => signIn()}>sign in</button>
      </main>
    </>
  );
}
